// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcvgfrufdmlgnmsfnpvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdmdmcnVmZG1sZ25tc2ZucHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTc4NDcsImV4cCI6MjA2NjUzMzg0N30.E348buDSGCow4fcLe8QWIqw-vcx2hWhZF9hw_jtHieo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);